"""Cross-language parity tests: Python `cubespec` vs TypeScript dashboard.

Golden values are generated by ``scripts/generate_parity_fixtures.mjs`` and
committed at ``python/tests/fixtures/parity_seed_1337.json``. Re-run that
script after any *intentional* algorithm change.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from cubespec.rng import Mulberry32
from cubespec.model import compute_outputs, compute_outputs_batch, set_mode
from cubespec.params import DEFAULT_CSP, PARAM_KEYS
from cubespec.doe import full_factorial, main_effects
from cubespec.sobol import sobol_indices


@pytest.fixture(autouse=True)
def _force_analytic_mode_for_legacy_fixture():
    """The committed parity fixture was generated against the analytic model.
    Pin that mode for tests in this module; restore the global afterwards."""
    set_mode("analytic")
    yield
    set_mode("calibrated")


FIXTURE_PATH = Path(__file__).parent / "fixtures" / "parity_seed_1337.json"


@pytest.fixture(scope="module")
def fixture() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


# ----------------------------------------------------------------------
# 1. PRNG bit-for-bit parity
# ----------------------------------------------------------------------
def test_mulberry32_first_64_values(fixture):
    rng = Mulberry32(seed=fixture["seed"])
    py_values = [rng.next() for _ in range(64)]
    ts_values = fixture["mulberry32_first_64"]
    assert len(py_values) == len(ts_values) == 64
    for i, (a, b) in enumerate(zip(py_values, ts_values)):
        # mulberry32 is integer-deterministic, so equality is exact in
        # IEEE-754 (both sides do the same `uint32 / 2^32` division).
        assert a == b, f"Drift at index {i}: py={a!r} ts={b!r}"


# ----------------------------------------------------------------------
# 2. Surrogate at the CSP means matches the dashboard exactly
# ----------------------------------------------------------------------
def test_surrogate_at_means_matches_dashboard(fixture):
    means = {k: fixture["csp"][k]["mean"] for k in PARAM_KEYS}
    py_out = compute_outputs(means)
    ts_out = fixture["surrogate_at_means"]
    for key in ("P7_def", "P8_strain", "P9_compressive_strength"):
        assert math.isclose(py_out[key], ts_out[key], rel_tol=0, abs_tol=1e-12), (
            f"{key}: py={py_out[key]!r} ts={ts_out[key]!r}"
        )


# ----------------------------------------------------------------------
# 3. 2² factorial main effects on (P1_dx, P4_Fx) match
# ----------------------------------------------------------------------
def test_full_2k_factorial_main_effects_match(fixture):
    # Restrict the 2⁷ design to a 2² subset by post-filtering rows where
    # the other five factors are at their mean (coded 0). Easier: build a
    # bespoke 2² evaluation that mirrors the fixture's coded layout.
    ts_eff = fixture["main_effects_2x2"]
    csp = DEFAULT_CSP
    base = {k: csp.params[k].mean for k in PARAM_KEYS}
    dx_lo = csp.params["P1_dx"].mean - csp.params["P1_dx"].sd
    dx_hi = csp.params["P1_dx"].mean + csp.params["P1_dx"].sd
    fx_lo = csp.params["P4_Fx"].mean - csp.params["P4_Fx"].sd
    fx_hi = csp.params["P4_Fx"].mean + csp.params["P4_Fx"].sd
    corners = [
        {**base, "P1_dx": dx_lo, "P4_Fx": fx_lo},
        {**base, "P1_dx": dx_hi, "P4_Fx": fx_lo},
        {**base, "P1_dx": dx_lo, "P4_Fx": fx_hi},
        {**base, "P1_dx": dx_hi, "P4_Fx": fx_hi},
    ]
    P9 = np.array([compute_outputs(c)["P9_compressive_strength"] for c in corners])
    dx_signs = np.array([-1, +1, -1, +1])
    fx_signs = np.array([-1, -1, +1, +1])
    eff_dx = (P9[dx_signs > 0].mean() - P9[dx_signs < 0].mean())
    eff_fx = (P9[fx_signs > 0].mean() - P9[fx_signs < 0].mean())
    assert math.isclose(eff_dx, ts_eff["P1_dx_on_P9"], abs_tol=1e-9)
    assert math.isclose(eff_fx, ts_eff["P4_Fx_on_P9"], abs_tol=1e-9)


# ----------------------------------------------------------------------
# 4. Sobol ST ranking on P9 matches the dashboard's canonical order
# ----------------------------------------------------------------------
def test_sobol_st_ranking_matches(fixture):
    df = sobol_indices(DEFAULT_CSP, n_base=2048, seed=fixture["seed"])
    P9 = df[df["output"] == "P9_compressive_strength"].copy()
    ranking = P9.sort_values("ST", ascending=False)["factor"].tolist()
    expected = fixture["sobol_ST_ranking_P9"]
    # Top-3 are numerically dominant (>99% of P9 variance combined) and
    # ranked deterministically: P4_Fx, P2_dy, P1_dx.
    assert ranking[:3] == expected[:3], (
        f"Top-3 ST ranking differs: py={ranking[:3]} expected={expected[:3]}"
    )
    # P0_rho and P3_dz drop out of P9 entirely (they only enter P7/P8).
    zero_factors = {f for f in ("P0_rho", "P3_dz")
                    if float(P9[P9["factor"] == f]["ST"].iloc[0]) < 1e-6}
    assert zero_factors == {"P0_rho", "P3_dz"}
