"""Generate a synthetic measured-vs-predicted dataset and plot it.

The CSV produced (`cube_lab_measurements.csv`) is intentionally
synthetic — the real lab measurements would replace it once available.
"""
from __future__ import annotations
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from cubespec import (
    DEFAULT_CSP, sample_independent, compute_outputs_batch,
)

OUT_PNG = Path(__file__).resolve().parent / "output" / "measured_vs_predicted.png"
OUT_CSV = Path(__file__).resolve().parent.parent / "cube_lab_measurements.csv"
OUT_PNG.parent.mkdir(exist_ok=True)


def main() -> None:
    rng = np.random.default_rng(42)
    n = 30
    X = sample_independent(DEFAULT_CSP, n=n, seed=42)
    P9_pred = compute_outputs_batch(X)[:, 2]
    noise = rng.normal(0.0, 1.0, size=n)  # ~1 MPa lab noise
    P9_meas = P9_pred + noise

    # Persist the synthetic dataset so other notebooks can load it.
    df = pd.DataFrame({
        "Run": np.arange(1, n + 1),
        "Strength_MPa": np.round(P9_meas, 3),
        "Notes": ["synthetic — generated by plot_measured_vs_predicted.py (seed=42)"] * n,
    })
    df.to_csv(OUT_CSV, index=False)

    lo = float(min(P9_pred.min(), P9_meas.min())) - 1
    hi = float(max(P9_pred.max(), P9_meas.max())) + 1
    fig, ax = plt.subplots(figsize=(6.5, 6.5), dpi=130)
    ax.plot([lo, hi], [lo, hi], "--", color="#0F172A", lw=1, label="y = x")
    ax.scatter(P9_pred, P9_meas, s=44, color="#3B82F6",
               edgecolor="white", linewidth=0.8, label="lab runs")
    ax.set_xlabel("Predicted P9 (MPa)")
    ax.set_ylabel("Measured P9 (MPa, synthetic)")
    ax.set_title("Measured vs predicted compressive strength (n = 30)")
    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_aspect("equal")
    ax.legend(frameon=False, loc="upper left")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(OUT_PNG, bbox_inches="tight")
    print(f"Wrote {OUT_PNG}")
    print(f"Wrote {OUT_CSV}")


if __name__ == "__main__":
    main()
