#!/usr/bin/env python3
"""Generate the final docs QA audit (markdown table + CSV evidence + coverage matrix).

Outputs:
    docs/qa-audit.md
    /mnt/documents/cubespec_docs_audit.csv
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DOCS = REPO / "docs"
MANIFEST = REPO / "dist" / "docs" / "manifest.json"
OUT_MD = DOCS / "qa-audit.md"
OUT_CSV = Path("/mnt/documents/cubespec_docs_audit.csv")

STUB_THRESHOLD = 50  # words


def status_for(entry: dict, text: str) -> str:
    if not entry["bytes"]:
        return "missing"
    if entry["word_count"] < STUB_THRESHOLD:
        return "stub_warning"
    if text.rstrip().lower().endswith("todo"):
        return "stub_warning"
    return "ok"


def main() -> int:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    rows = []
    for e in data["files"]:
        text = (REPO / e["path"]).read_text(encoding="utf-8", errors="replace")
        rows.append(
            {
                **e,
                "exists": True,
                "status": status_for(e, text),
            }
        )

    # ---------- CSV ----------
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "path",
                "exists",
                "bytes",
                "sha256_short",
                "word_count",
                "language",
                "batch",
                "status",
            ],
        )
        w.writeheader()
        for r in rows:
            w.writerow({k: r[k] for k in w.fieldnames})

    # ---------- Coverage matrix ----------
    manual_en = {p.stem for p in (DOCS / "manual").glob("[0-9][0-9]-*.md")}
    manual_gr = {p.stem for p in (DOCS / "manual" / "gr").glob("[0-9][0-9]-*.md")}
    tut_en = {p.stem.split("-", 1)[0] for p in (DOCS / "tutorials").glob("[0-9][0-9]-*.md")}
    tut_gr = {p.stem.split("-", 1)[0] for p in (DOCS / "tutorials" / "gr").glob("[0-9][0-9]-*.md")}

    manual_missing_gr = sorted(manual_en - manual_gr)
    tut_missing_gr = sorted(tut_en - tut_gr)

    # Glossary coverage: at least one occurrence in manuals/tutorials
    glossary_terms: list[str] = []
    glossary_path = DOCS / "reference" / "glossary-en.md"
    if glossary_path.exists():
        for line in glossary_path.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^\s*\*\*([A-Z][A-Za-z0-9 \-/]+?)\*\*", line)
            if m:
                glossary_terms.append(m.group(1).strip())
    glossary_terms = sorted(set(glossary_terms))[:40]  # cap for the table

    user_facing_corpus = ""
    for d in [(DOCS / "manual"), (DOCS / "tutorials")]:
        for p in d.rglob("*.md"):
            user_facing_corpus += "\n" + p.read_text(encoding="utf-8", errors="replace")

    glossary_uncovered = [
        t for t in glossary_terms if t.lower() not in user_facing_corpus.lower()
    ]

    # Dev contracts referenced from user-facing docs (Batch 7 augmentations)
    dev_files = [p.name for p in (DOCS / "dev").glob("*.md")]
    aug_targets = [
        DOCS / "thesis-paper-full-en.md",
        DOCS / "thesis-paper-full-gr.md",
        DOCS / "thesis-abstract.md",
        DOCS / "csp-parameters.md",
        DOCS / "cli.md",
        DOCS / "verification-and-validation.md",
        DOCS / "validation-report.md",
        DOCS / "media" / "demo_script.md",
    ]
    aug_corpus = "\n".join(
        p.read_text(encoding="utf-8", errors="replace")
        for p in aug_targets
        if p.exists()
    )
    dev_unreferenced = [d for d in dev_files if d not in aug_corpus]

    # ---------- Renderer log ----------
    rendered = []
    for name in [
        "cubespec_thesis_en",
        "cubespec_thesis_gr",
        "cubespec_manual_en",
        "cubespec_manual_gr",
        "cubespec_defence_en",
        "cubespec_defence_gr",
    ]:
        pdf = Path("/mnt/documents") / f"{name}.pdf"
        rendered.append(
            {
                "name": name,
                "exists": pdf.exists(),
                "bytes": pdf.stat().st_size if pdf.exists() else 0,
            }
        )

    # ---------- Markdown ----------
    counts = {"ok": 0, "stub_warning": 0, "missing": 0}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1

    lines: list[str] = []
    lines.append("# CubeSpec — Documentation QA Audit\n")
    lines.append(
        "_Auto-generated by `python/scripts/build_qa_audit.py`. "
        "Re-run after any documentation change to refresh the evidence table._\n"
    )

    lines.append("## Summary\n")
    lines.append(f"- Total Markdown files audited: **{len(rows)}**")
    lines.append(f"- ok: **{counts.get('ok', 0)}**")
    lines.append(f"- stub_warning: **{counts.get('stub_warning', 0)}**")
    lines.append(f"- missing: **{counts.get('missing', 0)}**\n")

    lines.append("## Renderer pipeline\n")
    lines.append("- Markdown bundling: `python/scripts/build_docs.py`")
    lines.append("- DOCX renderer: **pandoc** (`pandoc --toc --toc-depth=2 -t docx`)")
    lines.append("- PDF renderer: **LibreOffice** (DOCX → PDF, headless)")
    lines.append("- Manifest: `python/scripts/build_docs_manifest.py` → `dist/docs/manifest.json`\n")

    lines.append("### Rendered artifacts\n")
    lines.append("| Bundle | PDF exists | Size (bytes) |")
    lines.append("|---|---|---|")
    for r in rendered:
        lines.append(f"| `{r['name']}.pdf` | {'✅' if r['exists'] else '❌'} | {r['bytes']:,} |")
    lines.append("")

    lines.append("## Coverage matrix\n")
    lines.append("### Manual EN ↔ GR parity")
    if manual_missing_gr:
        lines.append("- ⚠️ Missing GR twins:")
        for s in manual_missing_gr:
            lines.append(f"  - `{s}`")
    else:
        lines.append("- ✅ All EN manual chapters have a GR twin.")
    lines.append("")

    lines.append("### Tutorials EN ↔ GR parity")
    if tut_missing_gr:
        lines.append("- ⚠️ Missing GR twins (by chapter prefix):")
        for s in tut_missing_gr:
            lines.append(f"  - `{s}`")
    else:
        lines.append("- ✅ All EN tutorials have a GR twin (filenames in Greek by design).")
    lines.append("")

    lines.append("### Glossary terms appearing in user-facing docs (sample of {})".format(len(glossary_terms)))
    if glossary_uncovered:
        lines.append("- ⚠️ Terms not found in `manual/` or `tutorials/`:")
        for t in glossary_uncovered:
            lines.append(f"  - {t}")
    else:
        lines.append("- ✅ Every sampled glossary term appears at least once.")
    lines.append("")

    lines.append("### Dev contracts cross-referenced from user-facing docs (Batch 7)")
    if dev_unreferenced:
        lines.append("- ⚠️ Dev files not yet referenced:")
        for d in dev_unreferenced:
            lines.append(f"  - `docs/dev/{d}`")
    else:
        lines.append("- ✅ Every `docs/dev/*.md` contract is linked from at least one user-facing doc.")
    lines.append("")

    # ---------- Word-parity matrix (Batch 10) ----------
    lines.append("### Word-parity matrix (GR manual ↔ EN manual)")
    lines.append("")
    lines.append("| Chapter | EN words | GR words | Ratio | Status |")
    lines.append("|---|---:|---:|---:|---|")
    parity_threshold = 0.90
    parity_target = 0.95
    parity_breaches: list[str] = []
    en_dir = DOCS / "manual"
    gr_dir = DOCS / "manual" / "gr"
    for en_path in sorted(en_dir.glob("[0-9][0-9]-*.md")):
        gr_path = gr_dir / en_path.name
        if not gr_path.exists():
            continue
        en_words = len(en_path.read_text(encoding="utf-8").split())
        gr_words = len(gr_path.read_text(encoding="utf-8").split())
        ratio = gr_words / en_words if en_words else 0.0
        if ratio >= parity_target:
            badge = "✅"
        elif ratio >= parity_threshold:
            badge = "⚠️"
        else:
            badge = "❌"
            parity_breaches.append(en_path.name)
        lines.append(
            f"| `{en_path.name}` | {en_words:,} | {gr_words:,} | "
            f"{ratio*100:.1f}% | {badge} |"
        )
    lines.append("")
    if parity_breaches:
        lines.append(
            f"- ⚠️ Below {parity_threshold*100:.0f}% parity: "
            + ", ".join(f"`{n}`" for n in parity_breaches)
        )
    else:
        lines.append(
            f"- ✅ All GR manual chapters at ≥ {parity_threshold*100:.0f}% "
            "of their EN twin's word count."
        )
    lines.append("")

    lines.append("## Evidence table\n")
    lines.append("| Path | Bytes | SHA-256 | Words | Lang | Batch | Status |")
    lines.append("|---|---:|---|---:|---|---|---|")
    for r in sorted(rows, key=lambda x: x["path"]):
        badge = {"ok": "✅", "stub_warning": "⚠️", "missing": "❌"}[r["status"]]
        lines.append(
            f"| `{r['path']}` | {r['bytes']:,} | `{r['sha256_short']}` | "
            f"{r['word_count']:,} | {r['language']} | {r['batch']} | {badge} {r['status']} |"
        )
    lines.append("")

    lines.append("## Reproducing this audit\n")
    lines.append("```bash")
    lines.append("python python/scripts/build_docs_manifest.py")
    lines.append("python python/scripts/build_docs.py --out dist/docs --copy-to /mnt/documents")
    lines.append("python python/scripts/build_qa_audit.py")
    lines.append("```")
    lines.append("")

    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"[qa-audit] wrote {OUT_MD} ({OUT_MD.stat().st_size} bytes)")
    print(f"[qa-audit] wrote {OUT_CSV} ({OUT_CSV.stat().st_size} bytes)")
    print(f"[qa-audit] status counts: {counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
